name: Feature Request
description: Suggest a feature

body:
  - type: textarea
    attributes:
      label: Description
      description: What is the feature you want to see?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Proposed sulution
    validations:
      required: true

  - type: textarea
    attributes:
      label: Alternatives considered
    validations:
      required: true
